n_records: 20_000
batch_size: 512
env_block_size: 16  # important for irm
seed: 215233
config_name: debug
savedir: "data/simulated/"

base_distrib: normal  # normal, exponential
n_bins: [16, 401]
n_bins_multiple_of: 16  # useful since dilation otherwise can fail
n_obs: [200, 10_000]
window_size: [0.5, 1.0]
loc: [0., 1.0]  # relative to support
scale: [0.01, 0.99]  # relative to support
min_scale: 1  # make sure not all eggs are in the same basket

mixture: false
n_comps: [1, 6] # number of mixture components
alpha: [0.25, 4.0]

multiplicate_overdispersion: true
od_sigma: [1e-6, 0.4]

rounding: true
rounding_stride: [1, 2, 5, 10]

negbin_background: true
disp_coef: [0.05, 2.0]
noise_ratio: [0.001, 0.75]

hydra:
    run:
        dir: "."
