epochs: 300
ensemble_size: 2
ckpt_every: 50
batch_size: 64
env_block_size: 16  # important for irm
plot_every: 100
clipnorm: 3.0
init_lr: 3e-4
# disc_updates: 1
min_lr: 1e-5
half_lr: 25  # before 10
train_gen_every: 1
max_reg: 0.0001
cycle_reg: 1.0
identity_reg: 1e-5
half_reg: 25
irm_rel_wt: 1.0
# tv_rel_wt: 1.0
seed: 1498163
# tv_order: 1
# huber_k: 2.0
reg_warmup: 5
train_dirs: [normal_mix]
ood_dirs: [expon_mix]
logdir: "."
init_expl: 0.5
min_expl: 0.01
half_expl: 10

band_lam: 0.025
band_lim: 100.0
band_tgt: 0.0

hydra:
    run:
        dir: "outputs/freegan/${hydra.job.override_dirname}"
    job_logging:
        formatters:
            simple:
                format: '%(message)s'
