epochs: 300
burnin: 0
pretrain_identity: 5
load_pretrained: false
pretrain_lr: 5e-4
use_replay: false
replay_capacity: 20_000
gen_filters: 32
gen_norm_layers: true
gen_dropout: false
ensemble_size: 1
ckpt_every: 50
batch_size: 64
replay_blocks: 2
env_block_size: 32  # important for irm
plot_every: 100
clipnorm: 10.0
init_lr: 5e-4
half_lr_every: 10
half_power: 0.75
smooth_init_lr: 1e-4
smooth_batch_size: 32
smooth_train_steps: 1
smooth_half_lr_every: 100000
smooth_lr_multiplier: 1.0
disc_lr_multiplier: 1.0
max_noise_ratio: 1.0
# disc_updates: 1
min_lr: 1e-6
half_lr: 0.00001  # before 10
train_gen_every: 1
train_disc_every: 1
train_smoother_every: 1
max_reg: 0.000
cycle_reg: 0.1
norm_reg: 0.0001
identity_reg: 1e-4
half_reg: 1000.0
irm_rel_wt: 1.0
# tv_rel_wt: 1.0
seed: 1498163
# tv_order: 1
# huber_k: 2.0
reg_warmup: 1
train_dirs: [normal_mix]
ood_dirs: [expon_mix]
logdir: "."
init_expl: 0.5
min_expl: 0.01
half_expl: 10

band_lam: 0.005
band_lim: 3.0
band_tgt: 0.0

# penalty for discrminator
disc_centering_weight: 1e-3
disc_grad_penalty_weight: 10.0

hydra:
    run:
        dir: "outputs/freegan_F/${hydra.job.override_dirname}"
    job_logging:
        formatters:
            simple:
                format: '%(message)s'
